"""initial schema

Revision ID: 90281a7271bd
Revises: 
Create Date: 2026-07-15 13:04:58.904297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90281a7271bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=120), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deal_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('documents', sa.JSON(), nullable=False),
    sa.Column('access_logs', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pitch_version_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_jobs_pitch_version_id'), ['pitch_version_id'], unique=False)

    op.create_table('fit_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fit_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fit_matches_investor_id'), ['investor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fit_matches_startup_id'), ['startup_id'], unique=False)

    op.create_table('mentors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('reputations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('ratings', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('startups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theses',
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('investor_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('pitches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pitches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pitches_startup_id'), ['startup_id'], unique=False)

    op.create_table('pitch_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('pitch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pitch_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pitch_versions_pitch_id'), ['pitch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitch_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pitch_versions_pitch_id'))

    op.drop_table('pitch_versions')
    with op.batch_alter_table('pitches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pitches_startup_id'))

    op.drop_table('pitches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('theses')
    op.drop_table('startups')
    op.drop_table('reputations')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    op.drop_table('messages')
    op.drop_table('mentors')
    with op.batch_alter_table('fit_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fit_matches_startup_id'))
        batch_op.drop_index(batch_op.f('ix_fit_matches_investor_id'))

    op.drop_table('fit_matches')
    with op.batch_alter_table('evaluation_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_jobs_pitch_version_id'))

    op.drop_table('evaluation_jobs')
    op.drop_table('deal_rooms')
    op.drop_table('bookings')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
